### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kaliiks** [kaliiks/BungeeCordPE#1]
- [ ] Server Close RequestPacket
- [ ] BungeeCord UDP Client
- [ ] SubServer Tick
- [ ] MultiThreading
- [ ] MCPE Packet encoding/decoding/reading
- [ ] Sending LoginPacket
- [ ] Response of PingPacket (Query)
